#!/bin/bash

userChoice=0
fileName="Power Plan Changer.desktop"
pathShortcut="/home/$USER/Desktop/"

clear

if [ ! -f "$pathShortcut$fileName" ]; then
	echo -e "[Desktop Entry]\n
Name=Power Plan Changer\n
Comment=Change power plans in lenovo laptop\n
Exec=$(pwd)/power-plan-changer\n
Icon=utilities-terminal\n
Terminal=true\n
Type=Application" > "$pathShortcut$fileName"
fi

clear

[ "$UID" -eq 0 ] || exec sudo "$0" "$@"

echo -e "For Lenovo Ideapad 5 Pro 14arh7, could work on other models\n"
echo -e "Pick an option:\n\n1) check viable power plans\n2) Intelligent Cooling\n3) Extreme Performance\n4) Battery Saving\n\n>\c"

read userChoice
clear

case $userChoice in
	"1") cat /sys/firmware/acpi/platform_profile_choices ;;
	"2") echo 'balanced' > /sys/firmware/acpi/platform_profile
		echo "Power plan is Balanced" ;;
	"3") echo 'performance' > /sys/firmware/acpi/platform_profile
		echo "Power plan is Performance" ;;
	"4") echo 'low-power' > /sys/firmware/acpi/platform_profile
		echo "Power plan is Battery Saving" ;;
	*) echo "No such option"
esac

sleep 3
exit
