#!/bin/bash

procId=$(echo $$)
currentPlan="null"
userChoice=0
fileName="Power Plan Changer.desktop"
pathShortcut="/home/$USER/Desktop/"
configPath=$(dirname $0)
shortcut
mainFunc=true

shortcut_create() { 
#This function is used for toggling shortcut creation
	toggleShortcut=0
	
	if [ $shortcut -eq "1" ]; then
		echo "on"
	else
		echo "off"
	fi
	
	echo -e "\nToggle it? [y/n]"
	read toggleShortcut
	
	#It writes into the config
	case $toggleShortcut in
	"y") if [ $shortcut -eq "1" ]; then
		echo shortcut=0 > "$configPath/ppc_conf"
	     elif [ $shortcut -eq "0"  ]; then
	     	echo shortcut=1 > "$configPath/ppc_conf"
	     fi ;;
	 "n") ;;
	 *) echo "No such option"	
	 
	 esac
}

clear

#This checks if the config file is present, if not it will create it with #default values
if [ ! -f "$configPath/ppc_conf" ]; then
	echo -e "shortcut=1;" > "$configPath/ppc_conf"
fi

source "$configPath/ppc_conf"

#This condition checks for existing shortcut, if not present it will create one
if [ ! -f "$pathShortcut$fileName" ] && [ $shortcut -eq "1" ]; then
	echo -e "[Desktop Entry]\n
Name=Power Plan Changer\n
Comment=Change power plans in lenovo laptop\n
Exec=$(pwd)/power-plan-changer\n
Icon=utilities-terminal\n
Terminal=true\n
Type=Application" > "$pathShortcut$fileName"
fi

#This checks if script is ran as sudo
if [ "$(id -u)" != "0" ]; then
    echo "This script requires sudo!"
    [ "$UID" -eq 0 ] || exec sudo "$0" "$@"
fi


#Main Body
while true;
do
	currentPlan=$(cat /sys/firmware/acpi/platform_profile)
	
	clear
	
	echo -e "For Lenovo Ideapad 5 Pro 14arh7, could work on other models\t \e]8;;https://github.com/FatPootis03\e\\@FatPootis03\e]8;;\e\\
	\nCurrent mode: $currentPlan\n"
	sleep 1
	echo -e "Pick an option:\n\n1) check viable power plans\n2) Intelligent Cooling\n3) Extreme Performance\n4) Battery Saving\n5) Shortcut creation\n6) Exit\n\n>\c"

	read userChoice
	clear

	case $userChoice in
		"1") cat /sys/firmware/acpi/platform_profile_choices
			sleep 2 ;;
		"2") echo 'balanced' > /sys/firmware/acpi/platform_profile
			echo "Power plan is Balanced" ;;
		"3") echo 'performance' > /sys/firmware/acpi/platform_profile
			echo "Power plan is Performance" ;;
		"4") echo 'low-power' > /sys/firmware/acpi/platform_profile
			echo "Power plan is Battery Saving" ;;
		"5") echo -e 'Shortcut creation: \c'
			shortcut_create ;;
		"6") sleep 1
			kill -9 $procId ;;	
		*)  sleep 1
			echo "No such option"
	esac
	
done

sleep 1
exit
